[{"ContainerToolsException.Message":"Сбой команды Docker с кодом завершения 1. 2024/09/24 17:21:32 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed #0 building with \"default\" instance using docker driver  #1 [internal] load build definition from Dockerfile #1 transferring dockerfile: 1.21kB 0.0s done #1 DONE 0.0s  #2 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0 #2 DONE 0.0s  #3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0 #3 DONE 0.1s  #4 [internal] load .dockerignore #4 transferring context: 2B done #4 DONE 0.0s  #5 [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:1e8c6666f3e31f96d22a5c77054589f85078a4850595421c6999395f26e79b9a #5 DONE 0.0s  #6 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:8.0 #6 DONE 0.0s  #7 [build 2/9] WORKDIR /src #7 CACHED  #8 [internal] load build context #8 transferring context: 686.07kB 0.1s done #8 DONE 0.1s  #9 [build 3/9] COPY [AuthService.Presentation/AuthService.Presentation.csproj, AuthService.Presentation/] #9 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.Presentation/AuthService.Presentation.csproj\": not found  #10 [build 5/9] COPY [AuthService.DataAccess/AuthService.DataAccess.csproj, AuthService.DataAccess/] #10 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.DataAccess/AuthService.DataAccess.csproj\": not found  #11 [build 4/9] COPY [AuthService.Buisness/AuthService.Buisness.csproj, AuthService.Buisness/] #11 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.Buisness/AuthService.Buisness.csproj\": not found ------  > [build 3/9] COPY [AuthService.Presentation/AuthService.Presentation.csproj, AuthService.Presentation/]: ------ ------  > [build 4/9] COPY [AuthService.Buisness/AuthService.Buisness.csproj, AuthService.Buisness/]: ------ ------  > [build 5/9] COPY [AuthService.DataAccess/AuthService.DataAccess.csproj, AuthService.DataAccess/]: ------ Dockerfile:14 --------------------   12 |     COPY [\"AuthService.Presentation/AuthService.Presentation.csproj\", \"AuthService.Presentation/\"]   13 |     COPY [\"AuthService.Buisness/AuthService.Buisness.csproj\", \"AuthService.Buisness/\"]   14 | >>> COPY [\"AuthService.DataAccess/AuthService.DataAccess.csproj\", \"AuthService.DataAccess/\"]   15 |     RUN dotnet restore \"./AuthService.Presentation/./AuthService.Presentation.csproj\"   16 |     COPY . . -------------------- ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.DataAccess/AuthService.DataAccess.csproj\": not found  View build details: docker-desktop://dashboard/build/default/default/w457mcmolgzz0gvm1wpyedbqo","ContainerToolsException.ErrorCode":"CTC1014","ContainerToolsException.StackTrace":"   в Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<BuildImageAsync>d__5.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<RebuildImageAsync>d__11.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchForDockerfileAsync>d__7.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<BuildAndLaunchAsync>d__5.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildAndLaunch.<ExecuteCoreAsync>d__200.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__30.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.FaultingUserFile.FilePath":"Dockerfile","ContainerToolsException.FaultingUserFile.LineStart":"","ContainerToolsException.FaultingUserFile.ColumnStart":"","ContainerToolsException.FaultingUserFile.LineEnd":"","ContainerToolsException.FaultingUserFile.ColumnEnd":"","ContainerToolsException.CommandLine.Program":"docker","ContainerToolsException.CommandLine.TelemetrySafeArguments":"build","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"2024/09/24 17:21:32 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed\r\n#0 building with \"default\" instance using docker driver\r\n\r\n#1 [internal] load build definition from Dockerfile\r\n#1 transferring dockerfile: 1.21kB 0.0s done\r\n#1 DONE 0.0s\r\n\r\n#2 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0\r\n#2 DONE 0.0s\r\n\r\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0\r\n#3 DONE 0.1s\r\n\r\n#4 [internal] load .dockerignore\r\n#4 transferring context: 2B done\r\n#4 DONE 0.0s\r\n\r\n#5 [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:1e8c6666f3e31f96d22a5c77054589f85078a4850595421c6999395f26e79b9a\r\n#5 DONE 0.0s\r\n\r\n#6 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:8.0\r\n#6 DONE 0.0s\r\n\r\n#7 [build 2/9] WORKDIR /src\r\n#7 CACHED\r\n\r\n#8 [internal] load build context\r\n#8 transferring context: 686.07kB 0.1s done\r\n#8 DONE 0.1s\r\n\r\n#9 [build 3/9] COPY [AuthService.Presentation/AuthService.Presentation.csproj, AuthService.Presentation/]\r\n#9 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.Presentation/AuthService.Presentation.csproj\": not found\r\n\r\n#10 [build 5/9] COPY [AuthService.DataAccess/AuthService.DataAccess.csproj, AuthService.DataAccess/]\r\n#10 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.DataAccess/AuthService.DataAccess.csproj\": not found\r\n\r\n#11 [build 4/9] COPY [AuthService.Buisness/AuthService.Buisness.csproj, AuthService.Buisness/]\r\n#11 ERROR: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.Buisness/AuthService.Buisness.csproj\": not found\r\n------\r\n > [build 3/9] COPY [AuthService.Presentation/AuthService.Presentation.csproj, AuthService.Presentation/]:\r\n------\r\n------\r\n > [build 4/9] COPY [AuthService.Buisness/AuthService.Buisness.csproj, AuthService.Buisness/]:\r\n------\r\n------\r\n > [build 5/9] COPY [AuthService.DataAccess/AuthService.DataAccess.csproj, AuthService.DataAccess/]:\r\n------\r\nDockerfile:14\r\n--------------------\r\n  12 |     COPY [\"AuthService.Presentation/AuthService.Presentation.csproj\", \"AuthService.Presentation/\"]\r\n  13 |     COPY [\"AuthService.Buisness/AuthService.Buisness.csproj\", \"AuthService.Buisness/\"]\r\n  14 | >>> COPY [\"AuthService.DataAccess/AuthService.DataAccess.csproj\", \"AuthService.DataAccess/\"]\r\n  15 |     RUN dotnet restore \"./AuthService.Presentation/./AuthService.Presentation.csproj\"\r\n  16 |     COPY . .\r\n--------------------\r\nERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref d9fab7fa-5e81-425a-91be-b97bbf78a8df::x5ulzbkwvdixwl5qbmc2ziipp: \"/AuthService.DataAccess/AuthService.DataAccess.csproj\": not found\r\n\r\nView build details: docker-desktop://dashboard/build/default/default/w457mcmolgzz0gvm1wpyedbqo"}]